<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'Приложение Просмотр Журналов показывает табличное отображение всех файлов журналов системы. Просмотр и поиск файлов журнала являются важным шагом в устранении неполадок операционной системы ClearOS.';
$lang['log_viewer_app_name'] = 'Просмотр журналов';
$lang['log_viewer_display'] = 'Показать';
$lang['log_viewer_entry'] = 'Запись в журнале';
$lang['log_viewer_export_to_file'] = 'Экспортировать в файл';
$lang['log_viewer_file'] = 'Файл журнала';
$lang['log_viewer_filter'] = 'Фильтр';
$lang['log_viewer_invalid_log_file'] = 'Файл журнала поврежден.';
$lang['log_viewer_logs'] = 'Журналы';
$lang['log_viewer_result_set_too_big'] = 'Набор результатов больше, чем максимум, который может быть выведен на экран. Используйте фильтр, чтобы уточнить Ваши результаты.';
$lang['log_viewer_show_full_line'] = 'Показывать полные строки';
