<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'Die Berichtsanzeige-App stellt alle Systemprotokolldateien tabellarisch dar.  Protokolldateien lesen und auswerten sind die Grundlage bei der Problembehebung Ihres Systems.';
$lang['log_viewer_app_name'] = 'Berichtsanzeige';
$lang['log_viewer_display'] = 'Anzeigen';
$lang['log_viewer_entry'] = 'Protokolleintrag';
$lang['log_viewer_export_to_file'] = 'In Datei exportieren';
$lang['log_viewer_file'] = 'Protokolldatei';
$lang['log_viewer_filter'] = 'Filtern';
$lang['log_viewer_invalid_log_file'] = 'Ungültige Protokolldatei.';
$lang['log_viewer_logs'] = 'Protokolle';
$lang['log_viewer_result_too_big'] = 'Das Ergebnis wurde abgeschnitten.  Das Ergebnis ist größer die maximale Größe (%s) die angezeigt wernden kann.  Bitte exportieren Sie die Datei um den Bericht vollständig anzusehen zu können. ';
$lang['log_viewer_show_full_line'] = 'Zeile vollständig anzeigen';
