<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'O Aplicativo Visualizador de Registros permite a exibição tabulada dos registros do sistema. A busca e visualização dos registros do sistema são essenciais e normalmente o primeiro passo para a solução de problemas no sistema.';
$lang['log_viewer_app_name'] = 'Visualizador de Registros';
$lang['log_viewer_display'] = 'Exibir';
$lang['log_viewer_entry'] = 'Entrada no Log';
$lang['log_viewer_export_to_file'] = 'Exportar para arquivo';
$lang['log_viewer_file'] = 'Arquivo de Registros';
$lang['log_viewer_filter'] = 'Filtrar';
$lang['log_viewer_invalid_log_file'] = 'Arquivos de registros inválido.';
$lang['log_viewer_logs'] = 'Registros';
$lang['log_viewer_result_too_big'] = 'Resultado parcial. O resultado é maior que (%s), que é o máximo que pode ser exibido. Por favor  exportar para arquivo para visualizar o conteúdo completo dos registros.';
$lang['log_viewer_show_full_line'] = 'Exibe linha inteira';
