<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'The Log Viewer app provides a tabular display of all system log files.  Viewing and searching of log files are essential and typically the first step in troubleshooting problems with your system.';
$lang['log_viewer_app_name'] = 'Log Viewer';
$lang['log_viewer_display'] = 'Display';
$lang['log_viewer_entry'] = 'Log Entry';
$lang['log_viewer_export_to_file'] = 'Export to File';
$lang['log_viewer_file'] = 'Log File';
$lang['log_viewer_filter'] = 'Filter';
$lang['log_viewer_invalid_log_file'] = 'Invalid log file.';
$lang['log_viewer_logs'] = 'Logs';
$lang['log_viewer_result_set_too_big'] = 'The result set is larger than the maximum that can be displayed.  Please use the filter to refine your results.';
$lang['log_viewer_show_full_line'] = 'Show Full Line';
