<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'Loggvisningen ger dig en tabellvy av alla systemfiler.   Att titta på och genomsöka loggfilerna är viktigt och normalt det första steget i att felsöka i ditt system.';
$lang['log_viewer_app_name'] = 'Loggvisning';
$lang['log_viewer_display'] = 'Visa';
$lang['log_viewer_entry'] = 'Logghändelse';
$lang['log_viewer_export_to_file'] = 'Exportera till fil';
$lang['log_viewer_file'] = 'Loggfil';
$lang['log_viewer_filter'] = 'Filter';
$lang['log_viewer_invalid_log_file'] = 'Ogiltig loggfil.';
$lang['log_viewer_logs'] = 'Loggar';
$lang['log_viewer_result_set_too_big'] = 'Resultatet är större än vad som kan visas.  Använd ett filter för att begränsa ditt resultat.';
$lang['log_viewer_show_full_line'] = 'Visa hel rad';
