<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'Loggvisar-appen ger en tabellvy av alla systemfiler.   Att titta på och genomsöka loggfilerna är viktigt och typiskt detta första steget i att felsöka i ditt system.';
$lang['log_viewer_app_name'] = 'Loggvisning';
$lang['log_viewer_display'] = 'Visa';
$lang['log_viewer_entry'] = 'Logghändelse';
$lang['log_viewer_export_to_file'] = 'Exportera till fil';
$lang['log_viewer_file'] = 'Loggfil';
$lang['log_viewer_filter'] = 'Filter';
$lang['log_viewer_invalid_log_file'] = 'Ogiltig loggfil.';
$lang['log_viewer_logs'] = 'Loggar';
$lang['log_viewer_result_set_too_big'] = 'The result set is larger than the maximum that can be displayed.  Please use the filter to refine your results.';
$lang['log_viewer_show_full_line'] = 'Visa hel rad';
