<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['log_viewer_app_description'] = 'Aplikacja Podgląd logów wyświetl w sposób tabelaryczny wszystkie systemowe pliki dzienników.  Podgląd i wyszukiwanie danych w logach jest podstawą i najczęściej pierwszym krokiem w rozwiązywaniu problemów z systemem..';
$lang['log_viewer_app_name'] = 'Podgląd logów';
$lang['log_viewer_display'] = 'Wyświetl';
$lang['log_viewer_entry'] = 'Wpis w dzienniku';
$lang['log_viewer_export_to_file'] = 'Eksportuj do pliku';
$lang['log_viewer_file'] = 'Plik dziennika';
$lang['log_viewer_filter'] = 'Filtr';
$lang['log_viewer_invalid_log_file'] = 'Nieprawidłowy plik dziennika.';
$lang['log_viewer_logs'] = 'Logi';
$lang['log_viewer_result_too_big'] = 'Wyniki zostały obcięte.  Zestaw wyników jest większy niż maksimum (%s) , które może zostać wyświetlone.  Prosimy dokonać eksportu do pliku aby zobaczyć pełną zawartość dziennika.';
$lang['log_viewer_show_full_line'] = 'Pokaż pełny wiersz';
